### ISSUE TITLE
createCard issue

### ISSUE THREAD

**Issue by hongwei1** [OpenBankProject/OBP-CLI#68] opened 2019-06-20 14:46 UTC
inside the `cards-import-template-v1.does` the last column, it is `customer-number`.
It should be `customer-id`.

I know we should use `customer-number` better, 
but for somereason we can not create `cusotmer-number` in api level.
eg: https://apiexplorersandbox.openbankproject.com/?tags=#OBPv3_1_0-createCustomer

So there is no sense to use real customer-number there for now.

**Comment by chrisjsimpson** [comment] 2019-06-21 12:39
@hongwei1 we use customer_number because that's what the end-user will put in during the import. The end-user does not know what the customer_id will be (because it's a randomly generated uid)

When we import a customer, the user wants to specify the customer number. 
After the customer is `POST`ed to Open Bank Project, then the customer number is updated:

https://github.com/OpenBankProject/OBP-CLI/blob/729ccd1704904f82432a126597d0acfa7c31e1d7/obp_python/importCustomers.py#L88


When customers import cards (createCard) , the customer number matched the customer number which the user imported.


Works as intended. I will close this issue

**Closed as completed by chrisjsimpson** 2019-06-21 12:39 UTC
